// Intentionally goofy "poorly translated" encouragement lines for loser confetti text.
// Use "{name}" as a placeholder for the player's name.
export const ENCOURAGEMENT_TEMPLATES = [
  "we love you {name}, victory was almostly",
  "{name} you are champion in our small hearts",
  "today no win, tomorrow big yes {name}",
  "{name} you give us fan feelings very hard",
  "you did losing but in style premium, {name}",
  "{name}, score maybe no, spirit mega yes",
  "all people clap for your near-win, {name}",
  "{name} you are not fail, just scenic route win",
  "game say no, we say wow {name}",
  "{name} your luck took bus, will arrive later",
  "heroic almost happened by {name}",
  "{name}, we are your fan club from now before",
  "you make proud sadness, good job {name}",
  "{name} is winner in emotional department",
  "defeat temporary, legend permanent {name}",
  "{name} you have us a fan! many fan!",
  "we trust your dice future, mr/ms {name}",
  "{name}, next round you cook the victory soup",
  "you dropped crown but kept sparkle, {name}",
  "{name} congratulations for trying extremely yes",
  "our applause machine is loud for {name}",
  "{name} almost win is still beautiful cinema",
  "dice was rude, but you was elegance, {name}",
  "{name} your effort has deluxe quality",
  "you are first place in heart leaderboard, {name}",
  "{name} the loss is fake news to us",
  "we send hugs with professional speed, {name}",
  "{name}, your comeback is loading please wait",
  "today pain, tomorrow champagne for {name}",
  "your roll was art museum, {name}",
  "{name} no trophy now, but vibes all day",
  "we see greatness trying to hatch, {name}",
  "sad result, happy hero: {name}",
  "{name} you are king queen of almost",
  "our respect level for {name} is over 9000 maybe",
  "{name} you spin bad luck into comedy gold",
  "you are fan magnet person, {name}",
  "{name}, never surrender the dice dream",
  "you got us cheering in broken english, {name}",
  "{name} the scoreboard is not your final story",
  "our village believes in {name} very strongly",
  "{name}, destiny had typo this round",
  "you lose little, you gain legend, {name}",
  "{name} your almost-win touched all souls",
  "bad dice day, good human day {name}",
  "{name} we print your bravery on t-shirt maybe",
  "respect invoice sent to {name}",
  "{name} you are certified cool under sadness",
  "we clap in seven languages for {name}",
  "{name}, keep rolling until universe says sorry",
  "even gravity supports your spirit, {name}",
  "{name} today was practice for epic tomorrow",
  "our hearts do confetti for {name}",
  "{name}, your fail has luxury finish",
  "you are champion of trying with style, {name}",
  "{name}, one loss cannot eat your sparkle",
  "we are your fans from future, {name}",
  "{name} please accept this emotional medal",
  "your vibes are undefeated, {name}",
  "{name}, close enough to win for dramatic effect",
  "we respect your hustle module, {name}",
  "{name} had unlucky dice but lucky charisma",
  "next match will apologize to {name}",
  "{name}, courage level: giant",
  "your attempt was very chef kiss, {name}",
  "{name} we cheer your almost masterpiece",
  "you are winner in our group chat, {name}",
  "{name}, this was character development episode",
  "defeat knocked, {name} answered politely",
  "{name} your spirit does not buffering",
  "we put your name in hall of nearly fame",
  "{name}, you are premium edition competitor",
  "your effort has crispy texture, {name}",
  "{name} is doing greatly under tragic dice weather",
  "big respect package delivered to {name}",
  "{name}, we ride at dawn for your rematch",
  "the universe misclicked, sorry {name}",
  "{name} you are fabulous in adversity mode",
  "we support your future victory arc, {name}",
  "{name} is still mega win in my browser tab lolzors",
  "epic near-victory detected for {name}, much wow very game",
  "{name} got lag spike from destiny server, not your fault",
  "brb crying, {name} was basically pwnage adjacent",
  "{name} did the roflcopter of courage, 10/10",
  "teh dice were cringe but {name} stayed based",
  "{name} unlocked achievement: Almostly Iconic Human",
  "omgwtfbbq the scoreboard forgot to respect {name}",
  "{name} pressed alt+f4 on sadness and kept smiling",
  "we has many fanz for {name}, no refunds",
  "{name} your gameplay is very ye olde internet legendary",
  "lol noob luck from dice, pro heart from {name}",
  "{name} gets plus ten internets from crowd",
  "epic fail? no, epic tale by {name}",
  "{name} you dropped crown but kept the swag packet",
  "sir {name}, you level up in my book to chapter 99",
  "{name} pressed the joystick very strategicly in spirit",
  "i gave {name} two extra lives on my fax machine",
  "{name} has enough coins to buy final boss groceries",
  "we plugged in the nintendo modem for {name} morale",
  "{name}, your hit points are emotionally full bars",
  "great run {name}, now install more turbo in controller",
  "{name} almost won the mario of this boardgame",
  "i told my VCR to save replay of {name} bravery",
  "{name} did a side quest to our hearts",
  "next round {name} will press the big A button of destiny",
  "{name}, your combo meter in my diary is x5000",
  "we call game hotline, they said {name} is very pro",
  "{name} got blue shell by life but still waved",
  "mission failed sucessfully by captain {name}",
  "{name} completed tutorial of greatness, boss fight soon",
  "gamer parent voice: {name} won internet cartridge today",
  "{name} your pixels are aligned for future triumph",
  "please insert quarter of hope for {name} rematch",
  "{name} turned defeat into downloadable content",
  "all your base of confidence belong to {name}",
  "{name} has very legal gamer energy from 2011",
  "lolzors mode activated: we still stan {name}",
  "{name} is certified xXx_legendcore_xXx",
  "my boomer patch notes say {name} buffed by friendship",
  "{name} almost speedran victory with office keyboard",
  "retro coach says {name} hold start to continue dreams",
  "{name}, we mailed your power-up by dial-up",
  "kek-tier effort from {name}, honestly iconic",
  "{name} has the high score in our family group email",
  "{name}, your luck software will update soon",
  "you are not last, you are dramatic first, {name}",
  "{name} your heart rolled all sixes",
  "crowd noise for {name} is maximum allowed",
  "{name}, your game face is inspiringly wow",
  "today the dice did comedy, not justice, {name}",
  "{name} remains iconic despite tiny tragedy",
  "we stan your persistence forever, {name}",
  "{name}, this loss is only decorative",
  "you make failure look fashionable, {name}",
  "{name}, your confidence has rocket fuel",
  "future trophy already shipping to {name}",
  "{name} no panic, legend process is normal",
  "we are proud with extra sauce, {name}",
  "{name}, continue operation: glorious comeback",
  "your near victory is still tasty, {name}",
  "{name} you are beloved by random strangers too",
  "we trust your dice destiny deeply, {name}",
  "{name}, your effort made weather better",
  "you got knocked but not unplugged, {name}",
  "{name}, keep smiling in tactical sadness",
  "our hearts vote {name} as honorary winner",
  "{name} your comeback trailer looked amazing",
  "all roads lead to future win for {name}",
];

export const getLoserEncouragements = (name) =>
  ENCOURAGEMENT_TEMPLATES.map((line) => line.replaceAll("{name}", name));
